import { useState, type CSSProperties } from "react";
import { ArrowRight, Check, ChevronRight, Clock3, Flame, Heart, MessageCircle, Play, Plus, Share2, Sparkles, Target, Users, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";

import { CommunityShell } from "./_shared/CommunityShell";

const lessons = [
  { id: 1, title: "Build your first AI workflow", series: "AI at work · 03", duration: "18 min", type: "Workshop", tone: "aqua", completed: false },
  { id: 2, title: "Prompt systems that survive contact with reality", series: "AI at work · 04", duration: "24 min", type: "Deep dive", tone: "coral", completed: false },
  { id: 3, title: "The 30-minute research sprint", series: "AI at work · 05", duration: "16 min", type: "Workshop", tone: "violet", completed: false },
];

const threads = [
  { initials: "MN", name: "Mina N.", time: "18m ago", text: "I turned the eval checklist into a little Notion template. The “what would change my mind?” prompt is gold.", likes: 12, replies: 4, color: "bg-[hsl(var(--fisl-violet))]" },
  { initials: "DS", name: "Devon S.", time: "1h ago", text: "Has anyone tried the workflow lesson with a sales call transcript? Curious where the human review step lives.", likes: 8, replies: 7, color: "bg-[hsl(var(--fisl-aqua))]" },
];

export function MemberHome() {
  const [activeNav, setActiveNav] = useState("Home");
  const [completed, setCompleted] = useState<number[]>([]);
  const [showAllLessons, setShowAllLessons] = useState(false);
  const [liked, setLiked] = useState<number[]>([]);
  const [showComposer, setShowComposer] = useState(false);
  const [composerText, setComposerText] = useState("");
  const [posted, setPosted] = useState(false);
  const [showPlan, setShowPlan] = useState(false);
  const [selectedLesson, setSelectedLesson] = useState<number | null>(null);

  const completeLesson = (id: number) => setCompleted((current) => current.includes(id) ? current.filter((lessonId) => lessonId !== id) : [...current, id]);
  const totalProgress = 42 + completed.length * 4;
  const visibleLessons = showAllLessons ? lessons : lessons.slice(0, 2);

  return (
    <CommunityShell role="member" active={activeNav} onNavigate={setActiveNav}>
      <div className="fisl-grid min-h-[calc(100dvh-72px)] px-5 py-7 sm:px-8 lg:px-10 lg:py-9">
        <div className="mx-auto max-w-[1320px]">
          <section className="fisl-rise grid gap-6 lg:grid-cols-[1.4fr_.6fr]">
            <div className="relative overflow-hidden rounded-[22px] bg-[hsl(var(--fisl-ink))] p-7 text-[hsl(var(--fisl-paper))] sm:p-9">
              <div className="absolute -right-8 -top-14 h-52 w-52 rounded-full border-[28px] border-[hsl(var(--fisl-lime)/.8)] opacity-80" />
              <div className="absolute -bottom-20 right-24 h-40 w-40 rounded-full border-[18px] border-[hsl(var(--fisl-coral)/.8)]" />
              <div className="relative max-w-[650px]">
                <div className="mb-6 flex items-center gap-2 text-[hsl(var(--fisl-lime))]"><span className="h-2 w-2 rounded-full bg-current" /><span className="fisl-mono text-[10px] font-bold uppercase tracking-[.18em]">Tuesday, 14 May · live room</span></div>
                <h1 className="fisl-display max-w-[620px] text-4xl font-bold leading-[.98] sm:text-6xl">Good morning, Ari.<br /><span className="text-[hsl(var(--fisl-lime))]">Make something</span> useful today.</h1>
                <p className="mt-6 max-w-[440px] text-sm leading-relaxed text-[hsl(var(--fisl-paper)/.68)]">You’re 2 lessons away from shipping your first AI workflow. The room is moving with you.</p>
                <Button onClick={() => setSelectedLesson(1)} className="mt-8 h-11 rounded-xl bg-[hsl(var(--fisl-lime))] px-5 font-bold text-[hsl(var(--fisl-ink))] hover:bg-[hsl(var(--fisl-lime)/.86)]"><Play size={15} className="mr-2 fill-current" /> Continue learning <ArrowRight size={16} className="ml-5" /></Button>
              </div>
            </div>
            <div className="fisl-rise fisl-rise-2 rounded-[22px] border border-[hsl(var(--fisl-ink)/.12)] bg-[hsl(var(--fisl-paper)/.75)] p-6 sm:p-7">
              <div className="flex items-start justify-between"><div><div className="fisl-mono text-[10px] font-bold uppercase tracking-[.18em] text-[hsl(var(--fisl-ink)/.5)]">Your momentum</div><div className="fisl-display mt-2 text-4xl font-bold">{totalProgress}%</div></div><div className="fisl-ring grid h-16 w-16 place-items-center rounded-full" style={{ "--value": `${totalProgress}%` } as CSSProperties}><div className="fisl-ring-inner grid h-12 w-12 place-items-center rounded-full"><Target size={19} /></div></div></div>
              <div className="mt-8 space-y-3"><div className="flex justify-between text-xs font-semibold"><span>AI at work pathway</span><span className="text-[hsl(var(--fisl-ink)/.5)]">4 / 10 lessons</span></div><Progress value={totalProgress} className="h-2 bg-[hsl(var(--fisl-ink)/.1)] [&>div]:bg-[hsl(var(--fisl-coral))]" /><div className="flex items-center gap-2 pt-1 text-xs text-[hsl(var(--fisl-ink)/.58)]"><Flame size={15} className="text-[hsl(var(--fisl-coral))]" /> 5 day learning streak <span className="ml-auto fisl-mono text-[10px]">+1 today</span></div></div>
              <div className="mt-7 border-t border-[hsl(var(--fisl-ink)/.1)] pt-5"><div className="flex items-center gap-2 text-xs"><span className="grid h-6 w-6 place-items-center rounded-md bg-[hsl(var(--fisl-lime))]"><Sparkles size={13} /></span><span><b>Next unlock:</b> Workflow clinic</span></div></div>
            </div>
          </section>

          <section className="fisl-rise fisl-rise-3 mt-8 grid gap-8 xl:grid-cols-[1fr_360px]">
            <div>
              <div className="mb-4 flex items-end justify-between"><div><div className="fisl-mono text-[10px] font-bold uppercase tracking-[.18em] text-[hsl(var(--fisl-ink)/.48)]">Keep going</div><h2 className="fisl-display mt-1 text-2xl font-bold">Up next in your path</h2></div><button type="button" onClick={() => setShowAllLessons(!showAllLessons)} className="flex items-center gap-1 text-xs font-bold underline decoration-[hsl(var(--fisl-coral))] decoration-2 underline-offset-4">{showAllLessons ? "Show less" : "View pathway"} <ChevronRight size={14} /></button></div>
              <div className="space-y-3">
                {visibleLessons.map((lesson, index) => { const isDone = completed.includes(lesson.id); return <div key={lesson.id} className="fisl-card-hover group flex items-center gap-4 rounded-2xl border border-[hsl(var(--fisl-ink)/.12)] bg-[hsl(var(--fisl-paper)/.75)] p-4 sm:p-5"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${lesson.tone === "aqua" ? "bg-[hsl(var(--fisl-aqua))]" : lesson.tone === "coral" ? "bg-[hsl(var(--fisl-coral))]" : "bg-[hsl(var(--fisl-violet))]"}`}><span className="fisl-mono text-sm font-bold">0{index + 3}</span></div><div className="min-w-0 flex-1"><div className="mb-1 flex flex-wrap items-center gap-2"><Badge className="rounded-md border-0 bg-[hsl(var(--fisl-ink)/.08)] px-2 py-0.5 text-[9px] uppercase tracking-[.12em] text-[hsl(var(--fisl-ink)/.65)]">{lesson.type}</Badge>{isDone && <span className="flex items-center gap-1 text-[10px] font-bold text-[hsl(var(--fisl-ink)/.5)]"><Check size={12} /> Completed</span>}</div><h3 className={`truncate text-sm font-bold sm:text-base ${isDone ? "text-[hsl(var(--fisl-ink)/.45)] line-through" : ""}`}>{lesson.title}</h3><div className="mt-1 flex items-center gap-2 text-xs text-[hsl(var(--fisl-ink)/.48)]"><span>{lesson.series}</span><span>·</span><span className="flex items-center gap-1"><Clock3 size={12} /> {lesson.duration}</span></div></div><button type="button" onClick={() => setSelectedLesson(lesson.id)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-[hsl(var(--fisl-ink)/.14)] bg-[hsl(var(--fisl-paper))] transition hover:bg-[hsl(var(--fisl-lime))]" aria-label={`Play ${lesson.title}`}><Play size={15} className="ml-0.5 fill-current" /></button><button type="button" onClick={() => completeLesson(lesson.id)} className={`hidden rounded-lg px-3 py-2 text-xs font-bold sm:block ${isDone ? "bg-[hsl(var(--fisl-ink)/.08)]" : "bg-[hsl(var(--fisl-ink))] text-[hsl(var(--fisl-paper))]"}`}>{isDone ? "Undo" : "Mark done"}</button></div> })}
              </div>
              <div className="mt-7 rounded-2xl border border-dashed border-[hsl(var(--fisl-ink)/.2)] p-5"><div className="flex items-start gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[hsl(var(--fisl-coral)/.18)]"><Plus size={16} /></div><div><h3 className="text-sm font-bold">What are you building?</h3><p className="mt-1 text-xs leading-relaxed text-[hsl(var(--fisl-ink)/.55)]">Drop a note in the room. Small experiments count as progress.</p></div><button type="button" onClick={() => setShowComposer(true)} className="ml-auto whitespace-nowrap rounded-lg border border-[hsl(var(--fisl-ink)/.16)] px-3 py-2 text-xs font-bold hover:bg-[hsl(var(--fisl-lime)/.45)]">Share update</button></div></div>
            </div>
            <aside><div className="mb-4 flex items-end justify-between"><div><div className="fisl-mono text-[10px] font-bold uppercase tracking-[.18em] text-[hsl(var(--fisl-ink)/.48)]">In the room</div><h2 className="fisl-display mt-1 text-2xl font-bold">Good conversations</h2></div><Users size={19} className="text-[hsl(var(--fisl-ink)/.45)]" /></div><div className="space-y-3">{threads.map((thread, index) => <article key={thread.name} className="rounded-2xl border border-[hsl(var(--fisl-ink)/.12)] bg-[hsl(var(--fisl-paper)/.7)] p-4"><div className="flex items-center gap-2.5"><div className={`grid h-8 w-8 place-items-center rounded-full text-[10px] font-bold ${thread.color}`}>{thread.initials}</div><div className="flex-1"><div className="text-xs font-bold">{thread.name}</div><div className="text-[10px] text-[hsl(var(--fisl-ink)/.45)]">{thread.time}</div></div><button type="button" onClick={() => setLiked((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index])} className="flex items-center gap-1 text-[11px] text-[hsl(var(--fisl-ink)/.5)]" aria-label={`Like post by ${thread.name}`}><Heart size={14} className={liked.includes(index) ? "fill-[hsl(var(--fisl-coral))] text-[hsl(var(--fisl-coral))]" : ""} /> {thread.likes + (liked.includes(index) ? 1 : 0)}</button></div><p className="mt-3 text-xs leading-relaxed text-[hsl(var(--fisl-ink)/.72)]">{thread.text}</p><div className="mt-3 flex items-center gap-1 text-[10px] font-bold text-[hsl(var(--fisl-ink)/.48)]"><MessageCircle size={13} /> {thread.replies} replies <Share2 size={13} className="ml-auto" /></div></article>)}</div><button type="button" onClick={() => setActiveNav("Explore")} className="mt-4 flex w-full items-center justify-between rounded-xl bg-[hsl(var(--fisl-aqua)/.35)] px-4 py-3 text-xs font-bold">Explore all conversations <ArrowRight size={15} /></button></aside>
          </section>

          <footer className="fisl-rise fisl-rise-4 mt-10 flex flex-col gap-4 border-t border-[hsl(var(--fisl-ink)/.1)] py-6 text-xs sm:flex-row sm:items-center"><div className="flex items-center gap-2 font-bold"><span className="grid h-6 w-6 place-items-center rounded-md bg-[hsl(var(--fisl-ink))] text-[hsl(var(--fisl-lime))]"><Sparkles size={12} /></span> FISL is a room, not a library.</div><div className="flex items-center gap-4 text-[hsl(var(--fisl-ink)/.5)] sm:ml-auto"><button type="button" onClick={() => setShowPlan(true)} className="hover:text-[hsl(var(--fisl-ink))]">Membership</button><button type="button" onClick={() => setActiveNav("Help")} className="hover:text-[hsl(var(--fisl-ink))]">Help</button></div></footer>
        </div>
      </div>

      {selectedLesson && <div className="fixed inset-0 z-50 grid place-items-center bg-[hsl(var(--fisl-ink)/.6)] p-5" onClick={() => setSelectedLesson(null)}><div className="w-full max-w-xl overflow-hidden rounded-2xl border border-[hsl(var(--fisl-paper)/.15)] bg-[hsl(var(--fisl-ink))] text-[hsl(var(--fisl-paper))] shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="relative grid aspect-video place-items-center bg-[hsl(var(--fisl-ink-soft))]"><div className="absolute inset-0 opacity-35" style={{ backgroundImage: "radial-gradient(circle at 30% 30%, hsl(var(--fisl-lime) / .8), transparent 22%), radial-gradient(circle at 75% 70%, hsl(var(--fisl-coral) / .65), transparent 24%)" }} /><button type="button" onClick={() => setSelectedLesson(null)} className="absolute right-4 top-4 grid h-8 w-8 place-items-center rounded-full bg-[hsl(var(--fisl-paper)/.12)]" aria-label="Close lesson"><X size={16} /></button><div className="relative grid h-16 w-16 place-items-center rounded-full bg-[hsl(var(--fisl-lime))] text-[hsl(var(--fisl-ink))]"><Play size={23} className="ml-1 fill-current" /></div><span className="absolute bottom-4 left-5 fisl-mono text-[10px] uppercase tracking-[.16em] text-[hsl(var(--fisl-paper)/.6)]">Protected member video · lesson 03</span></div><div className="p-6"><div className="fisl-mono text-[10px] uppercase tracking-[.18em] text-[hsl(var(--fisl-lime))]">AI at work · Workshop</div><h2 className="fisl-display mt-2 text-2xl font-bold">{lessons.find((lesson) => lesson.id === selectedLesson)?.title}</h2><div className="mt-5 flex gap-3"><Button onClick={() => { completeLesson(selectedLesson); setSelectedLesson(null); }} className="rounded-lg bg-[hsl(var(--fisl-lime))] font-bold text-[hsl(var(--fisl-ink))] hover:bg-[hsl(var(--fisl-lime)/.86)]"><Check size={15} className="mr-2" /> Mark lesson complete</Button><button type="button" onClick={() => setSelectedLesson(null)} className="rounded-lg px-4 text-sm text-[hsl(var(--fisl-paper)/.65)]">Close</button></div></div></div></div>}
      {showComposer && <div className="fixed inset-0 z-50 grid place-items-center bg-[hsl(var(--fisl-ink)/.55)] p-5" onClick={() => setShowComposer(false)}><div className="w-full max-w-md rounded-2xl bg-[hsl(var(--fisl-paper))] p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><h2 className="fisl-display text-2xl font-bold">Share with the room</h2><button type="button" onClick={() => setShowComposer(false)} aria-label="Close composer"><X size={17} /></button></div>{posted ? <div className="mt-6 rounded-xl bg-[hsl(var(--fisl-lime)/.45)] p-4 text-sm font-semibold">Posted. Your experiment is now in the room.</div> : <><textarea value={composerText} onChange={(event) => setComposerText(event.target.value)} className="fisl-input mt-5 min-h-28 w-full resize-none rounded-xl border border-[hsl(var(--fisl-ink)/.15)] bg-transparent p-3 text-sm" placeholder="I’m testing..." /><Button disabled={!composerText.trim()} onClick={() => setPosted(true)} className="mt-4 w-full rounded-xl bg-[hsl(var(--fisl-ink))] font-bold text-[hsl(var(--fisl-paper))]">Post update</Button></>}</div></div>}
      {showPlan && <div className="fixed inset-0 z-50 grid place-items-center bg-[hsl(var(--fisl-ink)/.55)] p-5" onClick={() => setShowPlan(false)}><div className="w-full max-w-sm rounded-2xl bg-[hsl(var(--fisl-paper))] p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex justify-between"><div><div className="fisl-mono text-[10px] uppercase tracking-[.18em] text-[hsl(var(--fisl-ink)/.5)]">Membership</div><h2 className="fisl-display mt-2 text-2xl font-bold">Builder plan</h2></div><button type="button" onClick={() => setShowPlan(false)} aria-label="Close membership"><X size={17} /></button></div><div className="mt-5 rounded-xl border border-[hsl(var(--fisl-ink)/.14)] p-4"><div className="flex justify-between text-sm font-bold"><span>Active subscription</span><span className="text-[hsl(var(--fisl-coral))]">$24 / month</span></div><p className="mt-2 text-xs leading-relaxed text-[hsl(var(--fisl-ink)/.55)]">Next payment on 02 June 2024. Includes all lessons, clinics, and the private room.</p></div><button type="button" onClick={() => setShowPlan(false)} className="mt-4 w-full rounded-xl border border-[hsl(var(--fisl-ink)/.16)] py-3 text-sm font-bold">Keep membership</button></div></div>}
    </CommunityShell>
  );
}