// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fisl-community/AdminOverview.tsx": () => import("../components/mockups/fisl-community/AdminOverview.tsx"),
  "./components/mockups/fisl-community/MemberHome.tsx": () => import("../components/mockups/fisl-community/MemberHome.tsx")
};
